[package]
name = "rust-img-download"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3"
thiserror = "1.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.39", features = ["full"] }
